on:
  release:
    types: [created]
  pull_request:
name: Build and Upload Release Artifacts
jobs:
  generate:
    name: Create release artifacts
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Artifact Bundle
        run: ./Scripts/build-release.sh ${{ github.event.release.name }}
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'swiftformat.artifactbundle.zip'